/**
 * Art pipeline constants (issues #32–#34).
 * All gameplay sprites are final hi-res redraws: player at 8× (#33), world
 * (helis, weapons, VFX, tiles, …) at 4× (#34). No placeholder upscales ship.
 */

/** Phaser texture key for the packed gameplay atlas. */
export const ATLAS_KEY = 'game-atlas';

/** Public path (under Vite `public/`) for the packed atlas image. */
export const ATLAS_IMAGE_PATH = 'atlas/game-atlas.png';

/** Public path for the Phaser hash atlas JSON. */
export const ATLAS_JSON_PATH = 'atlas/game-atlas.json';

/**
 * Integer upscale formerly applied to reference sprites for placeholders (#32).
 * Retained for ART-SPEC history; the packer no longer emits placeholders.
 */
export const ART_PLACEHOLDER_SCALE = 4;

/**
 * Scale of committed final player redraws vs Flash-era original pixel sizes.
 * 8× yields crisp textures when drawn into the 48×48 game sprite box on a
 * 1920×1080 canvas (issue #33).
 */
export const ART_PLAYER_FINAL_SCALE = 8;

/** Directory (repo-relative) of final player PNGs packed into the atlas. */
export const ART_PLAYER_FINAL_DIR = 'art/player';

/**
 * Scale of committed final world redraws (helis, weapons, VFX, tiles, …)
 * vs Flash-era original sizes. 4× keeps large frames packable while staying
 * crisp on the 1920×1080 canvas (issue #34).
 */
export const ART_WORLD_FINAL_SCALE = 4;

/** Directory (repo-relative) of final world PNGs packed into the atlas. */
export const ART_WORLD_FINAL_DIR = 'art/world';

/**
 * Full-bleed desert backdrop (not packed into the atlas — too large).
 * Generated by `npm run art:world`, copied to public/ by `npm run art:pack`.
 */
export const BG_IMAGE_KEY = 'game-bg';
export const BG_IMAGE_PATH = 'art/bg.png';
export const BG_ORIGINAL_W = 452;
export const BG_ORIGINAL_H = 322;

/** Max atlas edge length (power-of-two friendly ceiling for the packer). */
export const ATLAS_MAX_SIZE = 4096;

/** Padding between packed frames (px) to avoid bleed when filtering. */
export const ATLAS_PADDING = 2;
